version: '3.7'

services:
    microservice:
        build:
            context: ./microservice
        image: microservice
        container_name: microservice
        restart: unless-stopped
        ports:
            - "8000:8000"
        command: gunicorn -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker microservice:api