version: '3.7'

services:
    microservice:
        build:
            context: ./microservice
        image: few-threads-microservice
        container_name: few-threads-microservice
        restart: unless-stopped
        ports:
            - "8000:8000"
        # work in few threads
        command: gunicorn --workers=3 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker few-threads-microservice:api