version: '3.7'

services:
    microservice:
        build:
            context: ./microservice
        image: microservice
        container_name: microservice
        restart: unless-stopped
        ports:
            - "8000:8000"
        command: gunicorn --workers=3 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker microservice:api

    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        volumes:
            - ./redis/data:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        expose:
            - 6379
        command: redis-server /usr/local/etc/redis/redis.conf